function new_Opt = set_OptionPath(option,rie_Metric,type_Gauss)
        if (nargin == 1)
            option.out_GaussComponent_Name = [option.type_F,'_reSize',num2str(option.resized_Row),'M',num2str(option.resized_Col),'_bSize',num2str(option.block_Row),'M',num2str(option.block_Col),'M',num2str(option.block_Depth),...
                '_stSize',num2str(option.step_Row),'M',num2str(option.step_Col),'M',num2str(option.step_Temporal),'.mat'];
            option.numTime_Matrix_Path_GaussCom = [option.com_Path,'\',option.type_F,'_numTime_Matrix_reSize',num2str(option.resized_Row),'M',num2str(option.resized_Col),...
                '_bSize',num2str(option.block_Row),'M',num2str(option.block_Col),'M',num2str(option.block_Depth),...
                '_stSize',num2str(option.step_Row),'M',num2str(option.step_Col),'M',num2str(option.step_Temporal),'.mat'];
            new_Opt = option;
        elseif (nargin == 3)
            option.rie_Metric = rie_Metric; option.type_Gauss = type_Gauss;
            common_Suff = ['_stSize',num2str(option.step_Row),'M',num2str(option.step_Col),'M',num2str(option.step_Temporal),'_aG',num2str(option.alpha_Gauss),'_bG',num2str(option.beta_Gauss),...
                '_mC',num2str(option.min_EigCov),'_mG',num2str(option.min_EigGau),'_mR',num2str(option.min_EigRieCovDs),'_',rie_Metric,'_',type_Gauss,'_',option.type_Norm_RLDV,'.mat'];
            option.numTime_Matrix_Path_RieCovDs = [option.mat_Path,'\',option.type_F,'_numTime_Matrix_reSize',num2str(option.resized_Row),'M',num2str(option.resized_Col),'_bSize',num2str(option.block_Row),'M',num2str(option.block_Col),'M',num2str(option.block_Depth),...
                common_Suff];
            option.out_RieCovDs_Name = [option.type_F,'_reSize',num2str(option.resized_Row),'M',num2str(option.resized_Col),'_bSize',num2str(option.block_Row),'M',num2str(option.block_Col),'M',num2str(option.block_Depth),...
                common_Suff];
            option.dis_Matrix_Path = [option.mat_Path,'\',option.type_F,'_disMatrix_reSize',num2str(option.resized_Row),'M',num2str(option.resized_Col),'_bSize',num2str(option.block_Row),'M',num2str(option.block_Col),'M',num2str(option.block_Depth),...
                common_Suff];        
            option.res_NN_Path = [option.res_Path,'\','nn_Methods','\',option.type_F,'_',option.name_Dataset,'_numGallery',num2str(option.num_Gallery),'_reSize',num2str(option.resized_Row),'M',num2str(option.resized_Col),'_bSize',num2str(option.block_Row),'M',num2str(option.block_Col),'M',num2str(option.block_Depth),...
                common_Suff];
            option.res_Dis_Path = [option.res_Path,'\','dis_Methods','\',option.type_F,'_',option.name_Dataset,'_numGallery',num2str(option.num_Gallery),'_reSize',num2str(option.resized_Row),'M',num2str(option.resized_Col),'_bSize',num2str(option.block_Row),'M',num2str(option.block_Col),'M',num2str(option.block_Depth),...
                common_Suff];                 
            new_Opt = option;
        else
            new_Opt = option;
        end
        
end